@echo off
echo Nettoyage des fichiers de construction...
rd /s /q dist
echo Construction du site...
call npm run build
echo Copie de index.html vers 404.html...
copy dist\index.html dist\404.html
echo Création d'un fichier .nojekyll pour Github Pages...
type nul > dist\.nojekyll
echo Déploiement sur GitHub Pages...
npx gh-pages -d dist -r https://github.com/yannblanc75/yannblanc75Web.github.io.git -b main
echo Déploiement terminé!